context = h_init()
context.set_state('ProjectSummary', 'proposal_code', 'VLASS')
context.set_state('ProjectSummary', 'proposal_title', 'unknown')
context.set_state('ProjectSummary', 'piname', 'unknown')
context.set_state('ProjectSummary', 'observatory', 'Karl G. Jansky Very Large Array')
context.set_state('ProjectSummary', 'telescope', 'EVLA')
context.set_state('ProjectStructure', 'ppr_file', 'PPR.xml')
context.set_state('ProjectStructure', 'recipe_name', 'hifv_vlassSEIP')
vis='VLASS1.1.sb34899305.eb35070592.58164.31599563657.ms'
try:
 hifv_importdata(nocopy=True, vis=[vis], session=['session_1'])
 hif_editimlist(parameter_file='SEIP_parameter.list')
 hif_transformimagedata(datacolumn='data', clear_pointing=False, modify_weights=True, wtmode='nyq')
 hifv_restorepims(pipelinemode="automatic")
 hifv_flagtargetsdata(pipelinemode="automatic")
 hif_editimlist(parameter_file='CCIP_parameter.list', editmode='replace')
 hif_makeimages(hm_masking='manual')
 hifv_pbcor(pipelinemode="automatic")
 hif_makermsimages(pipelinemode="automatic")
 hif_makecutoutimages(pipelinemode="automatic")
 hifv_analyzestokescubes(pipelinemode="automatic")
 hifv_exportvlassdata(pipelinemode="automatic")
finally:
 h_save()
